Some suggested minor edits
OxfordCodeReviewNet/forum pull request #4
Opened 2020-06-14 12:32 UTC by fcooper8472

Mainly for language, readability, markdown style etc.

2020-06-14 12:37 UTC, fcooper8472 commented
I realise it would be confusing to open an issue that isn't about code review, so a couple of things here:

Each heading can be directly linked to (e.g. https://github.com/OxfordCodeReviewNet/forum#-what-are-code-reviews) so you don't need all the explicit html links.

The C++ core guidelines referenced here (https://github.com/OxfordCodeReviewNet/forum/blob/master/guidelines_for_reviewers.md#code-style) would be better in a static analysis section.  For code formatting you want [clang format](https://clang.llvm.org/docs/ClangFormat.html) which has built-in styles (that can be customised for your project) for LLVM, Google, Chromium, Mozilla, WebKit, Microsoft.

2020-06-15 07:31 UTC, tlestang commented
Thanks for the thorough review! Really helpful.
Re the links, I still prefer to keep them internal to the Markdown doc, i.e. independent of the final web address of the document. Anything against that ?

2020-06-15 07:57 UTC, tlestang commented on guidelines_for_reviewers.md
> +1. [Complex if statements](#complexity)
Could you just fix the indices?

2020-06-15 07:59 UTC, tlestang commented on remote.md
> +1. You can join any public workspace (or private if you were added to it) from your text editor. To join a workspace from the web-based editor, the workspace owner must first add you to it. Then in y
Same above

2020-06-15 08:01 UTC, tlestang requested changes
Looks great. Some lists only contain 1s as indices though. If you could just change that and I'll merge the PR

2020-06-15 09:22 UTC, fcooper8472 commented
> Thanks for the thorough review! Really helpful.
> Re the links, I still prefer to keep them internal to the Markdown doc, i.e. independent of the final web address of the document. Anything against that ?

No, that's fine!

2020-06-15 09:22 UTC, fcooper8472 commented on guidelines_for_reviewers.md
> +1. [Complex if statements](#complexity)
Not sure what you mean?

2020-06-15 09:23 UTC, fcooper8472 commented
> Looks great. Some lists only contain 1s as indices though. If you could just change that and I'll merge the PR

Ah, I see.  I think that's completely standard Markdown notation.  You list every item with a 1. and markdown figures out the appropriate number.  So if you ever want to insert an item in the middle of the list you don't have to re-number.

2020-06-15 11:24 UTC, tlestang commented
Ah ok! Makes sense! (I write in org-mode, which usually renumbers on the fly)

2020-06-15 11:25 UTC, tlestang approved these changes

2020-06-15 11:25 UTC, merged